/* DODSClientConfig.h.  Generated by configure.  */
/* DODSClientConfig.h.in.  Generated automatically from configure.in by autoheader.  */
// -*- C++ -*-

// (c) COPYRIGHT UCAR/HAO 1993-2002
// Please read the full copyright statement in the file COPYRIGHT.

#ifndef DODSClientConfig_h_
#define DODSClientConfig_h_



/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

//
#define _OS_HAS_SOCKLEN_T 1
//
#define _ACCEPT_USES_SOCKLEN_T 1
//
#define _GETSOCKNAME_USES_SOCKLEN_T 1
//
#define DODS_C_CONTROL 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the <sys/socket.h> header file.  */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Name of package */
/* #undef PACKAGE */

/* Version number of package */
/* #undef VERSION */


// Support for the Sun Pro compiler

#ifdef __SUNPRO_CC      // __SUNPRO_CC always defined for Sun CC 4.2
#ifdef ansi
#ifndef __STRICT_ANSI__
#define __STRICT_ANSI__
#endif // __STRICT_ANSI__
#endif // ansi
#endif // __SUNPRO_CC

// Support for the Microsoft compiler

#ifdef __WIN32         // __WIN32 always defined for Microsoft Visual C++ 5.0
#ifdef ansi
#ifndef __STRICT_ANSI__
#define __STRICT_ANSI__
#endif // __STRICT_ANSI__
#endif // ansi
#endif // __WIN32

// This code take cares of getting the necessary system header files if the API is not ANSI C++

#ifndef __STRICT_ANSI__
#if defined (unix) && !defined(_WINDOWS) && !defined(WIN32) && !defined(_WIN32) && !defined(__NT__) && !defined(_WINDOWS)&& !defined(OS2)
#include <unistd.h>
#endif // unix style
#if (defined (_WINDOWS) || defined(__NT__)) && !defined (unix)
#include <windows.h>
#include <process.h>
#endif // windows style
#endif // __STRICT_ANSI__


#endif // DODSClientConfig_h_
