Attributes {
    NC_GLOBAL {
        String Description " joinExisting test on netcdf Grid granules WITHOUT using scan@ncoords";
    }
    x {
        String Description "Test coordinate variable x.";
    }
    time {
        String Description "Test coordinate variable time.";
    }
    v {
        v {
            String Description "Test output data array v";
        }
        time {
            String Description "Test coordinate variable time.";
        }
        x {
            String Description "Test coordinate variable x.";
        }
    }
}
