# expect/tcl code to test constraintT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "
*****************************************
Entered constraintT::run

*****************************************
Build the data and build the post constraint
good
    post constraint: sym1.var1,sym2.var2
    should be: sym1.var1,sym2.var2

*****************************************
Returning from constraintT::run"

set dispatchTEST ./constraintT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "constraintT"
} else {
    fail "constraintT"
}

