# expect/tcl code to test failInitT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "I am building new failed cat
baseApp::initialize - failed"

set dispatchTEST ./failInitT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "failInitT"
} else {
    fail "failInitT"
}

