# expect/tcl code to test gzT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "
*****************************************
Entered gzT::run

*****************************************
uncompress a test file
Uncompression succeeded
result is correct
Contents of file correct
File is now cached

*****************************************
uncompress a test file, should be cached
Uncompression succeeded
result is correct
Contents of file correct
File is still cached

*****************************************
Returning from gzT::run"

set dispatchTEST ./gzT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "gzT"
} else {
    fail "gzT"
}

