# expect/tcl code to test initT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "I am building new cat
I am building new dog, using FUNINIT with no termination

*****************************************
Entered initT::run

*****************************************
Using TheCat and TheDog

*************************************
correct cat

*************************************
correct dog

*****************************************
Returning from initT::run
I am destroying the cat"

set dispatchTEST ./initT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "initT"
} else {
    fail "initT"
}

