# expect/tcl code to test lockT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "
*****************************************
Entered lockT::run

*****************************************
lock, then try to lock again
get first lock
try to lock again
failed to get lock, good
The cache dir ./testsuite/cache is already locked

*****************************************
unlock

*****************************************
lock the cache, create another cache and try to lock
locking first
creating second
locking second
failed to lock the cache, good

*****************************************
unlock the first cache

*****************************************
lock the second cache
got the lock, good

*****************************************
unlock the second cache

*****************************************
Returning from lockT::run"

set dispatchTEST ./lockT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "lockT"
} else {
    fail "lockT"
}

