# expect/tcl code to test resplistT
# pcw
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global dispatchTEST

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "
*****************************************
Entered resplistT::run

*****************************************
add the 5 response handlers
successfully added resp0
successfully added resp1
successfully added resp2
successfully added resp3
successfully added resp4

*****************************************
try to add resp3 again
failed to add resp3 again, good

*****************************************
finding the handlers
found resp4
found resp3
found resp2
found resp1
found resp0

*****************************************
removing resp2
successfully removed resp2
successfully added resp2 back
found resp2

*****************************************
Returning from resplistT::run"

set dispatchTEST ./resplistT

dispatch_start

if ![string compare $test_out $comp_output] { # check comp_output
    pass "resplistT"
} else {
    fail "resplistT"
}

