#!/bin/bash

input=$(
        cat << EOF
             <Value>libdap-3.21.1-666</Value>
             <Value>libdap-3.21.1</Value>
EOF
)


echo "$input" | sed -E \
    -e 's@<Value>[0-9]*\.[0-9]*\.[0-9]*</Value>@<Value>removed version</Value>@g' \
    -e 's@<Value>[a-zA-Z._]*-[0-9]+\.[0-9]+\.[0-9]+</Value>@<Value>removed version</Value>@g' \
    -e 's@dmrpp:version="[[0-9]]*\.[[0-9]]*\.[[0-9]]*"@removed dmrpp:version@g' 

    
    
    
    
    
    
    On OSX this bash script:
#!/bin/bash

input=$(
        cat << EOF
             <Value>libdap-3.21.1-666</Value>
             <Value>libdap-3.21.1</Value>
             dmrpp:version="3.20.13"
EOF
)

echo "$input"
echo "------------------------"
echo "$input" | sed -E \
    -e 's@<Value>[0-9]*\.[0-9]*\.[0-9]*</Value>@<Value>removed version</Value>@g' \
    -e 's@<Value>[a-zA-Z._]*-[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?</Value>@<Value>removed version</Value>@g' \
    -e 's@dmrpp:version="[0-9]+\.[0-9]+\.[0-9]+"@removed dmrpp:version@g' 
    
Is intended to the text value of the Value fields with the text "removed fields". Why doesn't it work?