#ifndef _HDFSP_ENUM_TYPE_H
#define _HDFSP_ENUM_TYPE_H

enum SPType
{ OTHERHDF, TRMML2_V6, TRMML3A_V6, TRMML3B_V6, TRMML3C_V6, TRMML2_V7, TRMML3S_V7, TRMML3M_V7, CER_AVG, CER_ES4, CER_CDAY, CER_CGEO, CER_SRB, CER_SYN, CER_ZAVG, OBPGL2, OBPGL3, MODISARNSS };

enum SPCV_FS
{TRMML3A_V6_HEI,TRMML3_V7_NLAYER, TRMML3_NTHRSH_ZO,TRMML3_NTHRSH_HB,TRMML3_NTHRSH_SRT};
#endif
