#ifndef _HDFSP_ENUM_TYPE_H
#define _HDFSP_ENUM_TYPE_H

enum SPType
{ OTHERHDF, TRMML2, TRMML3, CER_AVG, CER_ES4, CER_CDAY, CER_CGEO, CER_SRB,
                CER_SYN, CER_ZAVG, OBPGL2, OBPGL3, MODISARNSS };

#endif
