# Test the freeform date server side function with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from bescmdln_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

bescmdln_start "testsuite/ssfunc/ff_date_func.1.bescmd"
compare_stdout "testsuite/ssfunc/ff_date_func.1.bescmd.baseline" "ServerSide Function DDX: freeform_handler date_time()" 0

