# Test the hdf5 handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

bescmdln_start "testsuite/ssfunc/geoarray_func_badargs.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_badargs.bescmd.baseline" "ServerSide Function: geoarray() bad arguments" 1

bescmdln_start "testsuite/ssfunc/geoarray_func_basic.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_basic.bescmd.baseline" "ServerSide Function: geoarray() basic" 1

bescmdln_start "testsuite/ssfunc/geoarray_func_mixednotations_1.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_mixednotations_1.bescmd.baseline" "ServerSide Function: geoarray() mixed notaions #1" 1

bescmdln_start "testsuite/ssfunc/geoarray_func_mixednotations_2.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_mixednotations_2.bescmd.baseline" "ServerSide Function: geoarray() mixed notaions #2" 1

bescmdln_start "testsuite/ssfunc/geoarray_func_negativenotations.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_negativenotations.bescmd.baseline" "ServerSide Function: geoarray() negative notations" 1


bescmdln_start "testsuite/ssfunc/geoarray_func_wholearray.bescmd"
compare_stdout "testsuite/ssfunc/geoarray_func_wholearray.bescmd.baseline" "ServerSide Function: geoarray() whole array" 1


