# Test the hdf5 handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

bescmdln_start "testsuite/ssfunc/geogrid_func_badargs.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_badargs.bescmd.baseline" "ServerSide Function: geogrid() bad arguments" 1 match

bescmdln_start "testsuite/ssfunc/geogrid_func_basic.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_basic.bescmd.baseline" "ServerSide Function: geogrid() basic" 0

bescmdln_start "testsuite/ssfunc/geogrid_func_swapcoords.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_swapcoords.bescmd.baseline" "ServerSide Function: geogrid() swap coordinates" 0 match

bescmdln_start "testsuite/ssfunc/geogrid_func_timeselect.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_timeselect.bescmd.baseline" "ServerSide Function: geogrid() time selection" 0

bescmdln_start "testsuite/ssfunc/geogrid_func_wholearray.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_wholearray.bescmd.baseline" "ServerSide Function: geogrid() whole array" 0


