# Test the geogrid server side function with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from bescmdln_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

bescmdln_start "testsuite/ssfunc/geogrid_func_badargs.bescmd"
compare_stdout "testsuite/ssfunc/geogrid_func_badargs.bescmd.baseline" "ServerSide Function: geogrid() bad arguments" 1 match

