#!/bin/bash

bln_color=800000
imprvd_color=008000

echo "AddImportPath(u'"`pwd`"')" > AllInOne.vsz_header
rm AllInOne.vsz_plots


files="bln_*.csv imprvd_*.csv"
echo "There are "`echo $files | wc -w`" files."
for i in $files 
do

   

    if [[ $i == "bln_"* ]]
    then
        collection="bln_";
        color=$bln_color;
    elif [[ $i == *"imprvd_"* ]]
    then 
        collection="imprvd_";
        color=$imprvd_color;
    else
        collection="unknwn_";
        color=00FF00
    fi
    
    echo Collection: $collection

    test_name=`echo $i | sed s/.csv//g`
    echo test_name: $test_name
    
    echo "ImportFileCSV(u'"$test_name.csv"', headermode='1st', linked=True)" >> AllInOne.vsz_header

    echo "# ---- Graph of"$test_name >> AllInOne.vsz_plots
    echo "Add('xy', name='$test_name', autoadd=False)" >> AllInOne.vsz_plots
    echo "To('$test_name')" >> AllInOne.vsz_plots
    echo "Set('markerSize', u'1pt')" >> AllInOne.vsz_plots
    echo "Set('color', u'#$color')" >> AllInOne.vsz_plots
    echo "Set('xData', u'"$test_name"_time')" >> AllInOne.vsz_plots
    echo "Set('yData', u'"$test_name"_mem_heap_B')" >> AllInOne.vsz_plots
    echo "Set('MarkerLine/color', u'#$color')" >> AllInOne.vsz_plots
    echo "To('..')" >> AllInOne.vsz_plots

done

cat AllInOne.vsz_header AllInOne.vsz_page_setup AllInOne.vsz_plots > AllInOne.vsz



