#!/bin/bash

echo "TestName, baseline_max_memory, improved_max_memory"

files="bln_*.csv"
#echo "There are "`echo $files | wc -w`" files."
for primary in $files 
do

    test_name=`echo $primary | sed -e "s/bln_//g" -e "s/imprvd_//g" -e "s/.csv//g"`
    
    #echo "test_name: "$test_name
        
    baseline_name="bln_"$test_name
    #echo baseline_name: $baseline_name
    imprvd_name="imprvd_"$test_name

    #echo imprvd_name: $imprvd_name
    
    bln_max=`awk 'BEGIN{max=0;}{val=substr($2,1,length($2)-1)+0.0;; if(NR>1){ if(max<val){max=val}}}END{print max;}' $baseline_name.csv `
    #echo "$baseline_name: "$bln_max

    imprvd_max=`awk 'BEGIN{max=0;}{val=substr($2,1,length($2)-1)+0.0;; if(NR>1){ if(max<val){max=val}}}END{print max;}' $imprvd_name.csv `
    #echo "$imprvd_name: "$imprvd_max
    
    echo "$test_name, $bln_max, $imprvd_max"
done
    
    