#!/bin/bash

baseline_color=800000
imprvd_color=008000

echo "AddImportPath(u'"`pwd`"')" > StackedPlots.vsz_header
rm StackedPlots.vsz_plots


files="bln_*.csv"
echo "There are "`echo $files | wc -w`" files."
for primary in $files 
do

    test_name=`echo $primary | sed -e "s/bln_//g" -e "s/imprvd_//g" -e "s/.csv//g"`
    
    echo "test_name: "$test_name
        
    baseline_name="bln_"$test_name
    echo baseline_name: $baseline_name
    imprvd_name="imprvd_"$test_name

    echo imprvd_name: $imprvd_name

    echo "ImportFileCSV(u'"$baseline_name.csv"', headermode='1st', linked=True)" >> StackedPlots.vsz_header
    echo "ImportFileCSV(u'"$imprvd_name.csv"', headermode='1st', linked=True)" >> StackedPlots.vsz_header
    
    echo "# ---- Graph of "$imprvd_name >> StackedPlots.vsz_plots >> StackedPlots.vsz_plots
    echo "Add('graph', name='$test_name', autoadd=False)" >> StackedPlots.vsz_plots
    echo "To('$test_name')" >> StackedPlots.vsz_plots
    echo "Add('axis', name='x', autoadd=False)" >> StackedPlots.vsz_plots
    echo "To('x')" >> StackedPlots.vsz_plots
    echo "Set('label', u'$test_name test time (ms)')" >> StackedPlots.vsz_plots
    echo "To('..')" >> StackedPlots.vsz_plots
    echo "Add('axis', name='y', autoadd=False)" >> StackedPlots.vsz_plots
    echo "To('y')" >> StackedPlots.vsz_plots
    echo "Set('label', u'Memory Allocated (bytes)')" >> StackedPlots.vsz_plots
    echo "Set('direction', 'vertical')" >> StackedPlots.vsz_plots
    echo "To('..')" >> StackedPlots.vsz_plots

    echo "# ---- XYPlot of "$baseline_name >> StackedPlots.vsz_plots
    echo "Add('xy', name='$baseline_name', autoadd=False)" >> StackedPlots.vsz_plots
    echo "To('$baseline_name')" >> StackedPlots.vsz_plots
    echo "Set('markerSize', u'1pt')" >> StackedPlots.vsz_plots
    echo "Set('color', u'#$baseline_color')" >> StackedPlots.vsz_plots
    echo "Set('xData', u'"$baseline_name"_time')" >> StackedPlots.vsz_plots
    echo "Set('yData', u'"$baseline_name"_mem_heap_B')" >> StackedPlots.vsz_plots
    echo "Set('MarkerLine/color', u'#$baseline_color')" >> StackedPlots.vsz_plots
    echo "To('..')" >> StackedPlots.vsz_plots

    echo "# ---- XYPlot of "$imprvd_name >> StackedPlots.vsz_plots
    echo "Add('xy', name='$imprvd_name', autoadd=False)" >> StackedPlots.vsz_plots
    echo "To('$imprvd_name')" >> StackedPlots.vsz_plots
    echo "Set('markerSize', u'1pt')" >> StackedPlots.vsz_plots
    echo "Set('color', u'#$imprvd_color')" >> StackedPlots.vsz_plots
    echo "Set('xData', u'"$imprvd_name"_time')" >> StackedPlots.vsz_plots
    echo "Set('yData', u'"$imprvd_name"_mem_heap_B')" >> StackedPlots.vsz_plots
    echo "Set('MarkerLine/color', u'#$imprvd_color')" >> StackedPlots.vsz_plots
    echo "To('..')" >> StackedPlots.vsz_plots
    echo "To('..')" >> StackedPlots.vsz_plots

done

cat StackedPlots.vsz_header StackedPlots.vsz_page_setup StackedPlots.vsz_plots > StackedPlots.vsz



