#!/bin/sh

what=$1

os=`uname`

echo "BES is currently installed in @prefix@"
else
    echo "Please set the environment variable OPENDAP_SERVER_ROOT"
    exit;
fi

case $what in
stop)
    if [ ! -f "${OPENDAP_SERVER_ROOT}"/run/bes.pid ]
    then
	echo "BES Listener is not currently running..."
	exit 1
    fi
    echo "Shutting down bes listener..."
    (cat "$OPENDAP_SERVER_ROOT"/run/bes.pid | cut -d' ' -f2 | xargs kill -INT) 2> /dev/null
    ;;
start)
    if [ -f "${OPENDAP_SERVER_ROOT}"/run/bes.pid ]
    then
	echo "BES is already running..."
	cat "${OPENDAP_SERVER_ROOT}"/run/bes.pid
	exit 1
    fi
    "${OPENDAP_SERVER_ROOT}"/sbin/besd $*
    ;;
restart)
    if [ ! -f "${OPENDAP_SERVER_ROOT}"/run/bes.pid ]
    then
	echo "BES Listener is not currently running"
	exit 1
    fi
    echo "Shutting down BES listener..."
    (cat "${OPENDAP_SERVER_ROOT}"/run/bes.pid | cut -d' ' -f2 | xargs kill -INT) 2> /dev/null
    sleep 5
    if [ -f ${OPENDAP_SERVER_ROOT}/run/bes.pid ]
    then
	echo "Unable to stop the BES listener"
	exit 1
    fi
    "${OPENDAP_SERVER_ROOT}"/sbin/besd $*
    ;;
status)
    if [ ! -f "${OPENDAP_SERVER_ROOT}"/run/bes.pid ]
    then
	echo "BES Listener is not currently running"
	exit 1
    fi
    echo "BES Listener is currently running:"
    cat "${OPENDAP_SERVER_ROOT}"/run/bes.pid
    ;;
*)
    echo "USAGE: besctl (start|stop|restart)"
    exit 1
    ;;
esac

