#!/bin/sh

DEFAULT_CONF="--with-dap=${OPENDAP_ROOT} --prefix=${OPENDAP_ROOT}"

# ncesg
./configure ${DEFAULT_CONF} --with-modules=/project/cedar/src/pwest/esg/EarthSystemGrid/src/ncesg_module.o --with-packages="-L/project/cedar/src/pwest/esg/EarthSystemGrid/src -lncesg -L/project/cedar/src/pwest/packages/netcdf-3.5.0/libsrc -lnetcdf"


# cedar
#./configure ${DEFAULT_CONF} --with-modules=/project/cedar/src/pwest/opendap/DODS/src/cedar-handler/cedar_module.o --with-packages="/project/cedar/src/pwest/opendap/DODS/src/cedar-handler/cedar_persistence.o -L/project/cedar/src/pwest/opendap/DODS/src/cedar-handler -lcedar-handler -L/project/cedar/src/pwest/packages/Cedar-2.0.1/library -lCedar"

# fits
#./configure --with-modules=${OPENDAP_ROOT}/lib/fits_module.o --with-packages="-L${OPENDAP_ROOT}/lib -lfits-handler -L/project/cedar/src/pwest/packages/lib -lcfitsio" ${DEFAULT_CONF}

# cdf

