Attributes {
    SDS_Array_dim_0 {
        String name "fakeDim0";
    }
    SDS_Grid_dim_0 {
        String name "fakeDim1";
    }
    Main_Vgroup {
        String Main_Attr "Hello";
    }
    Array_Vgroup {
        String Array_Attr "Hello";
    }
    Grid_Vgroup {
        String Grid_Attr "Hello";
    }
    GR_Vgroup {
        String GR_Attr "Hello";
    }
    Vdata_Vgroup {
        String Vdata_Attr "Hello";
    }
}
