Attributes {
    BT_diff_SO2 {
        String hdf_name "BT_diff_SO2";
        Float32 _FillValue -9999.00000;
    }
    Time {
        String hdf_name "Time";
        Float64 _FillValue -9999.000000000000;
    }
    Longitude {
        String hdf_name "Longitude";
        Float64 _FillValue -9999.000000000000;
    }
    Latitude {
        String hdf_name "Latitude";
        Float64 _FillValue -9999.000000000000;
    }
    NC_GLOBAL {
        String coremetadata "elided";
        String StructMetadata_1 "elided";
        String StructMetadata_0 "elided";
        String HDFEOSVersion "HDFEOS_V2.12";
        String creation_date "Tue Mar 27 22:24:16 PDT 2012";
        String NCL_Version "6.0.0";
        String system "elided";
        String conventions "None";
        String hdf_source "AIRS.2010.10.26.163.L1B.AIRS_Rad.v5.0.0.0.G10300110532.hdf";
        String title "NCL: convert-HDF-to-netCDF";
    }
}
