# This is centOS 7 rpm build. 

name: centos7 rpm

env:
  prefix: ${{ github.workspace }}/build
  jobs: 16

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  centos-7-build:
    runs-on: ubuntu-latest
    container:
      image: opendap/centos7_hyrax_builder:1.3

    # packages step not here because the Docker container holds them already
    steps:
      - name: cache-bison
        id: bison-centos7-docker    # Used below in the 'if'. So i changed the id to match the if statement below
        uses: actions/cache@v2
        with:
          path: $prefix/deps
          key: c7-pkg               # changed the key to avoid conflict with the id.

      # build the dependencies so that we don't have to update the container
      # every time the deps change.
      - name: build bison dependency
        # this statement should use the cache step id not the key
        if: steps.bison-centos7-docker.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/OPENDAP/hyrax-dependencies
          cd hyrax-dependencies
          make --jobs=$jobs bison

      - name: checkout
        uses: actions/checkout@v2

      - name: configure
        run: |
          autoreconf -fiv
          ./configure --enable-developer --prefix=$prefix

      - name: make
        run: make rpm --jobs=$jobs

      # $HOME is /github/home
      - name: upload to s3
        run: |
          yum install -y awscli
          aws s3 cp $HOME/rpmbuild/RPMS s3://opendap.github.actions.build --recursive

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

          