# This is the distcheck build stage from .travis.yml

name: distcheck

env:
  prefix: ${{ github.workspace }}/build
  jobs: 16

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-16.04
    
    steps:
      - name: Packages
        run: sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev
     
      - name: cache-bison
        id: cache-bison   # Used below in the 'if'
        uses: actions/cache@v2
        with:
          path: $prefix/deps
          key: bison-${{ runner.os }}

      - name: build bison dependency
        if: steps.cache-bison.outputs.cache-hit != 'true'
        run: |
          pwd
          git clone https://github.com/OPENDAP/hyrax-dependencies
          cd hyrax-dependencies
          make --jobs=$jobs bison

      - name: checkout
        uses: actions/checkout@v2

      - name: autoreconf
        run: autoreconf --force --install --verbose

      - name: configure
        run: ./configure --prefix=$prefix  --enable-developer

      - name: Make
        run: make distcheck -j7 

