## This is the sonar scan stage from .travis.yml

name: sonar scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    sonarscan:
        runs-on: ubuntu-16.04

        steps:
          - name: Checkout repo
            uses: actions/checkout@v2

          - name: Installs
            run: |
              sudo apt-get update
              sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev gcovr

          - name: Download and unzip Sonar scanner file
            run: |
              set -x
              sudo mkdir /downloads/sonar-scanner -p 
              cd /downloads/sonar-scanner
              sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip 
              sudo unzip sonar-scanner-cli-4.2.0.1873-linux.zip -d /opt/ 
              # ls -lart
              sudo mv /opt/sonar-scanner-4.2.0.1873-linux/ /opt/sonar-scanner 
              # ls /opt/sonar-scanner
              # ls /opt/sonar-scanner/conf
              cd /opt/sonar-scanner
              sudo chown -R $USER:$USER /opt/sonar-scanner/conf/sonar-scanner.properties 
              sudo echo "sonar.host.url=https://sonarcloud.io" >> /opt/sonar-scanner/conf/sonar-scanner.properties 
              sudo echo "sonar.login=$SONAR_LOGIN" >> /opt/sonar-scanner/conf/sonar-scanner.properties
              export ssb="/opt/sonar-scanner/bin"
              # ls -la ${ssb}
              export PATH=${ssb}:${PATH}
              sonar-scanner -v
                           
          - name: Configure
            run: |
              autoreconf -i
              ./configure --prefix=$prefix --enable-developer --enable-coverage             

          - name: build wrapper & scan
            run: |
              sudo wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
              sudo unzip build-wrapper-linux-x86.zip
              export LD_LIBRARY_PATH=$(pwd)/build-wrapper-linux-x86
              ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make -j7
              /opt/sonar-scanner/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
              curl -s https://sonarcloud.io/api/project_badges/quality_gate?project=OPENDAP-libdap4 | grep "QUALITY GATE PASS"
              
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

