# This is the source distribution package build

name: source distribution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    source-distribution:
        runs-on: ubuntu-16.04

        steps: 
          - name: Checkout repo
            uses: actions/checkout@v2

          - name: Installs
            run: |
              sudo apt-get update
              sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev awscli

          - name: Configure
            run: autoreconf -i

          # Make both a libdap-<version> and libdap-snapshot tar.gz. This will simplify
          # other operations that use the libdap source code like the bes build.
          - name: Build source distro package
            run: |
              sudo mkdir -p $HOME/package
              ./configure
              make dist -j7
              sudo cp libdap-*.tar.gz $HOME/package
              sudo cp libdap-*.tar.gz $HOME/package/libdap-snapshot.tar.gz;

          - name: upload to s3
            run: aws s3 cp $HOME/package s3://opendap.github.actions.build --recursive

            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}


