HTTP/1.0 200 OK
XDODS-Server: *
XOPeNDAP-Server:*
XDAP: *
Date: *
Last-Modified: *
Content-Type: *
Content-Description: *

Attributes {
    /Dataset1 {
        String HDF5_OBJ_FULLPATH "/Dataset1";
    }
    /Group1/ {
        String HDF5_OBJ_FULLPATH "/Group1/";
    }
    /Group1/Group2/ {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/";
    }
    /Group1/Group2/Dataset2 {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Dataset2";
    }
    /Group1/Group2/Dataset3 {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Dataset3";
    }
    /Group1/Group2/Dataset4 {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Dataset4";
    }
    /Group1/Group2/Group3/ {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Group3/";
    }
    /Group1/Group2/Group3/Dataset4 {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Group3/Dataset4";
    }
    /Group1/Group2/Group3/Group4/ {
        String HDF5_OBJ_FULLPATH "/Group1/Group2/Group3/Group4/";
    }
}
