HTTP/1.0 200 OK
XDODS-Server: *
XOPeNDAP-Server: *
XDAP: *
Date: *
Last-Modified: *
Content-Type: text/plain
Content-Description: dods_das

Attributes {
    this_is_a_large_group_name {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/";
    }
    this_is_a_large_group_name0 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name0/";
    }
    this_is_a_large_group_name1 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name1/";
    }
    this_is_a_large_group_name10 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name10/";
    }
    this_is_a_large_group_name11 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name11/";
    }
    this_is_a_large_group_name12 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name12/";
    }
    this_is_a_large_group_name13 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name13/";
    }
    this_is_a_large_group_name14 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name14/";
    }
    this_is_a_large_group_name15 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name15/";
    }
    this_is_a_large_group_name16 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name16/";
    }
    this_is_a_large_group_name17 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name17/";
    }
    this_is_a_large_group_name18 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name18/";
    }
    this_is_a_large_group_name19 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name19/";
    }
    this_is_a_large_group_name2 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name2/";
    }
    this_is_a_large_group_name20 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name20/";
    }
    this_is_a_large_group_name21 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name21/";
    }
    this_is_a_large_group_name22 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name22/";
    }
    this_is_a_large_group_name23 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name23/";
    }
    this_is_a_large_group_name24 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name24/";
    }
    this_is_a_large_group_name25 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name25/";
    }
    this_is_a_large_group_name26 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name26/";
    }
    this_is_a_large_group_name27 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name27/";
    }
    this_is_a_large_group_name28 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name28/";
    }
    this_is_a_large_group_name29 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name29/";
    }
    this_is_a_large_group_name3 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name3/";
    }
    this_is_a_large_group_name30 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name30/";
    }
    this_is_a_large_group_name31 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name31/";
    }
    this_is_a_large_group_name32 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name32/";
    }
    this_is_a_large_group_name33 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name33/";
    }
    this_is_a_large_group_name34 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name34/";
    }
    this_is_a_large_group_name35 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name35/";
    }
    this_is_a_large_group_name36 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name36/";
    }
    this_is_a_large_group_name37 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name37/";
    }
    this_is_a_large_group_name38 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name38/";
    }
    this_is_a_large_group_name39 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name39/";
    }
    this_is_a_large_group_name4 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name4/";
    }
    this_is_a_large_group_name40 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name40/";
    }
    this_is_a_large_group_name41 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name41/";
    }
    this_is_a_large_group_name42 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name42/";
    }
    this_is_a_large_group_name43 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name43/";
    }
    this_is_a_large_group_name44 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name44/";
    }
    this_is_a_large_group_name45 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name45/";
    }
    this_is_a_large_group_name46 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name46/";
    }
    this_is_a_large_group_name47 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name47/";
    }
    this_is_a_large_group_name48 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name48/";
    }
    this_is_a_large_group_name49 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name49/";
    }
    this_is_a_large_group_name5 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name5/";
    }
    this_is_a_large_group_name6 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name6/";
    }
    this_is_a_large_group_name7 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name7/";
    }
    this_is_a_large_group_name8 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name8/";
    }
    this_is_a_large_group_name9 {
        String HDF5_OBJ_FULLPATH "/this_is_a_large_group_name/this_is_a_large_group_name9/";
    }
}
