HTTP/1.0 200 OK
XDODS-Server: *
XOPeNDAP-Server: *
XDAP: *
Date: *
Last-Modified: *
Content-Type: *
Content-Description: dods_das

Attributes {
    H5_GLOBAL {
        String HDF5_OBJ_FULLPATH "H5_GLOBAL";
        Byte attr1%20withspace 97, 98, 99, 100, 101, 102, 103, 104, 105, 0;
    }
    g1.1%20withspace {
        String HDF5_OBJ_FULLPATH "/g1.1 withspace/";
    }
    dset1.1.1%20withspace {
        String HDF5_OBJ_FULLPATH "/g1.1 withspace/dset1.1.1 withspace";
    }
}
