HTTP/1.0 200 OK
XDODS-Server: 3.0
XOPeNDAP-Server: 3.0
XDAP: *
Date: *
Last-Modified: *
Content-Type: text/plain
Content-Description: dods_das

Attributes {
    HDF5_ROOT_GROUP {
        String Dataset "Dataset";
        g1 {
        }
    }
    /Dataset {
        String HDF5_OBJ_FULLPATH "/Dataset";
        Int32 Attribute 8;
    }
    /g1/ {
        String HDF5_OBJ_FULLPATH "/g1/";
        Int32 Attribute 8;
    }
}
