HTTP/1.0 200 OK
XDODS-Server:*
XOPeNDAP-Server:*
XDAP: *
Date: *
Last-Modified: *
Content-Type: *
Content-Description: *

Attributes {
    H5_GLOBAL {
        String HDF5_OBJ_FULLPATH "H5_GLOBAL";
        Byte attr1%22withquot 97, 98, 99, 100, 101, 102, 103, 104, 105, 0;
    }
    /g1.1%22withquot/ {
        String HDF5_OBJ_FULLPATH "/g1.1"withquot/";
    }
    /g1.1%22withquot/dset1.1.1%22withquot {
        String HDF5_OBJ_FULLPATH "/g1.1"withquot/dset1.1.1"withquot";
    }
}
