HTTP/1.0 200 OK
XDODS-Server: *
XOPeNDAP-Server: *
XDAP: *
Date: *
Last-Modified: *
Content-Type: *
Content-Description: dods_das

Attributes {
    comp1 {
        String HDF5_OBJ_FULLPATH "/comp1";
    }
    string1 {
        String HDF5_OBJ_FULLPATH "/string1";
    }
    string2 {
        String HDF5_OBJ_FULLPATH "/string2";
    }
    string3 {
        String HDF5_OBJ_FULLPATH "/string3";
    }
    string4 {
        String HDF5_OBJ_FULLPATH "/string4";
    }
}
