# Basic HDF-EOS tests

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global host

set testdir hdf-testfiles
set test_name "hdfeos"

dap_hdf4_handler_all "${testdir}" "GridFile" {UTMGrid.Data%20Fields.Vegetation\[0:5\]\[0:5\]}
dap_hdf4_handler_all "${testdir}" "PointFile"
dap_hdf4_handler_all "${testdir}" "SwathFile"

