/* ClientConfig.h.  Generated by configure.  */
/* ClientConfig.h.in.  Generated from configure.in by autoheader.  */
#ifndef ClientConfig_h_
#define ClientConfig_h_

#include "config.h"

// Support for the Sun Pro compiler

#ifdef __SUNPRO_CC      // __SUNPRO_CC always defined for Sun CC 4.2
#ifdef ansi
#ifndef __STRICT_ANSI__
#define __STRICT_ANSI__
#endif // __STRICT_ANSI__
#endif // ansi
#endif // __SUNPRO_CC

// Support for the Microsoft compiler

#ifdef __WIN32         // __WIN32 always defined for Microsoft Visual C++ 5.0
#ifdef ansi
#ifndef __STRICT_ANSI__
#define __STRICT_ANSI__
#endif // __STRICT_ANSI__
#endif // ansi
#endif // __WIN32

// This code take cares of getting the necessary system header files if the API is not ANSI C++

#ifndef __STRICT_ANSI__
#if defined (unix) && !defined(_WINDOWS) && !defined(WIN32) && !defined(_WIN32) && !defined(__NT__) && !defined(_WINDOWS)&& !defined(OS2)
#include <unistd.h>
#endif // unix style
#if (defined (_WINDOWS) || defined(__NT__)) && !defined (unix)
#include <windows.h>
#include <process.h>
#endif // windows style
#endif // __STRICT_ANSI__


#endif // ClientConfig_h_
