#!/bin/bash





for logFile in $@
do

   awk 'BEGIN{level=0; lastSubjTime=-1.0;}{ \
        split($0,fields,"\\]\\["); \
        state=fields[4]; \
        subjTime=fields[5]; \
        job_name=fields[7]; \
        job_elapsed=fields[9]; \
        
        if(lastSubjTime==-1.0){ \
            lastSubjTime = subjTime; \
        } \
        
        
        elapsed_between = subjTime - lastSubjTime; \
        
        if(lastState="STARTED" && state=="STOPPED"){
            leaked[level] += 0.0;
        }
        else {
            leaked[level] += elapsed_between;
        }
        
        
        
        if(state=="STARTED"){ \
            
            
            level++; \
            indent=""; \
            for(i=0; i<level ;i++){ \
                indent = indent " "; \
            } \

            printf("%f %s%s %s elapsed_between: %f \n",subjTime, indent, state, job_name,elapsed_between); \
    
        } \
        else if(state=="STOPPED"){ \
                        
            if( elapsed[level]!=0) { \
                diff = job_elapsed - elapsed[level]; \
                diffPercent = 100.0 * diff / job_elapsed; \
            } \
            else { \
                diff = 0.0; \
                diffPercent = 0.0; \
            } \

            printf("%f %s%s %s elapsed: %f sum_children_elapsed: %f  diff: %f ms (%f%%) elapsed_between: %f ms leaked: %f ms level: %d\n", subjTime, indent, state, job_name,  job_elapsed,  elapsed[level], diff, diffPercent, elapsed_between, leaked[level], level); \

            leaked[level] = 0.0; \

            elapsed[level] = 0.0; \
            level--; \
            
            
            
            indent=""; \
            for(i=0; i<level ;i++){ \
                indent = indent " "; \
            } \
            elapsed[level] += job_elapsed; \
        }\
        
        lastSubjTime = subjTime; \
        lastState =  state; \
   }' $logFile



done

