#!/bin/bash
#

reps=4
verbose=yes

for i in small_aggregations TRMM_3A11 TRMM_3B42 GPM_3IMERGHH AIRX3STD 
do
    logFile=${i}_r_${reps}_timing.log
    if test -n $verbose
    then
	echo "Working on $i aggregation timing evaluation. log: $logFile"
	echo "./timeTest -r $reps $i/*.xml > $logFile 2>&1"
    fi
    ./timeTest -r $reps $i/*.xml > $logFile 2>&1   
done