#!/bin/bash
#

reps=1

args=`getopt "r:" $*`
if test $? != 0
then
	echo "Usage: mkCurlTests [-r reps] servername:port/hyrax_end_point"
	echo "Example: mkCurlTests -r 4 128.0.0.1:8080/opendap"
	exit 2
fi

set -- $args

for i
do
    case "$i"
    in
        -r)
            reps=$2; 
            echo "Reps set to $reps"
            shift;
            shift;;
        --)
            shift; break;;
    esac
done

# now process all of the bescmd files...


server=$1

directories="heap_analysis small_aggregations TRMM_3A11 TRMM_3B42 GPM_3IMERGHH AIRX3STD"
#directories="AIRX3STD"
for dir in $directories
do
    for bescmd in `grep -l dds $dir/*.xml`
    #for bescmd in $dir/*.xml
    do
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"  
        echo "bescmd: $bescmd"  
        
        # <bes:setContainer name="catalogContainer" space="catalog">/agg/acdisc.gsfc.nasa.gov/AIRX3STD.006_Aggregation_2002.ncml</bes:setContainer>
        
        resourceID=`grep "setContainer" $bescmd | awk '{ split($0,s,">"); split(s[2],v,"<"); printf("%s",v[1]); }' -`
        #echo "ResourceID: $resourceID"
        
        # <bes:constraint>Temperature_A[0:8][0:23][0:179][0:359]</bes:constraint>
        # constraint=`grep "constraint" $i | awk '{split($0,s,">"); split(s[2],v,"<"); printf("%s",v[1]); }' - | sed -e "s/\[/\\\\\\\\\\\\[/g" -e "s/\]/\\\\\\\\\\\\]/g" `
        # constraint=`grep "constraint" $i | awk '{split($0,s,">"); split(s[2],v,"<"); gsub("\\\[","\\\\\\\[",v[1]); gsub("\\\]","\\\\\\\]",v[1]); printf("%s",v[1]); }' -  `

        constraint=`grep "constraint" $bescmd | awk '{split($0,s,">"); split(s[2],v,"<"); gsub("\\\[","\\\\\[",v[1]); gsub("\\\]","\\\\\]",v[1]); printf("%s",v[1]); }' -  `

        #echo "CE: $constraint"
        
        
        #  <bes:get type="dods" definition="d1" />
        
        type=`grep "bes:get" $bescmd | awk '{split($2,s,"="); split(s[2],v,"\""); printf("%s",v[2]);}' -`
        
        #echo "Response Type: $type"
        
        url="http://$server$resourceID.$type"
        
        if [ -n "$constraint" ] 
        then
            url="$url?$constraint"
        fi
        
        #echo ""
        echo "request_url: $url"

        
        curlCmd=$bescmd.curl.cmd
        curlResult=$bescmd.curl.result
        curlTime=$bescmd.curl.time
        
        echo "url = $url" > $curlCmd
        echo "-s" >> $curlCmd
        echo "-o $curlResult" >> $curlCmd
        # echo "--trace-ascii -" >> $curlCmd

        #echo ""
        echo "curl_cmd: $curlCmd"
        echo "reps: $reps"
        
        rm -f $curlTime

        repCount=0
        while [ $repCount -lt $reps ]
        do
            { time curl -K $curlCmd 2>$curlResult; } 2>>$curlTime
            repCount=$[repCount + 1] 
        done  
      
    done

done