#!/bin/bash

reps=1


for command in $@
do

    logFile=$command".log"
    result=$command".result"
 
    # echo "Processing command " $command " reps: " $reps
    besstandalone -r $reps -c $prefix/etc/bes/bes.conf -d "$logFile,timing,h5" -i $command > $result
    
    runs=`grep ELAPSED $logFile |  grep -E "get (dds|das|dods|dmr|dap)" | wc | awk '{print $1;}' -`
    
    # echo runs: $runs
    if [ $runs != $reps ]; then
        echo "ERROR: Failed to complete all scheduled reps of command $command. Skipping results."
    else 
    
            
        times=`grep ELAPSED $logFile |  grep -E "get (dds|das|dods|dmr|dap)" | awk '{ split($0,s,"["); print s[10];}' - | sed "s/]//g"`
        
        # echo "times: "$times
        
        metrics=`echo $times | awk 'BEGIN{sum=0;}{ for(i=1; i<=NF ;i++){sum=sum+$i;} print sum, sum/NF;}' -`
        
        sum=`echo $metrics | awk '{print $1}' -`
        avg=`echo $metrics | awk '{print $2}' -`
    
        echo $command: $avg ms avg time for $reps reps.
    fi
    
done






