#!/bin/bash

set -e
export BES_BUILD=main
# - export RUNTESTFLAGS="-v"
export LD_LIBRARY_PATH="/home/travis/install/deps/lib:$LD_LIBRARY_PATH"
echo "LD_LIBRARY_PATH - $LD_LIBRARY_PATH" >&2
autoreconf --force --install --verbose
./configure $CONFIGURE_OPTIONS --disable-dependency-tracking --prefix=$prefix --with-dependencies=$prefix/deps --enable-developer
make -j16
make install
besctl start
