#!/bin/bash
set -e
TEST_LOG_INVENTORY="/tmp/bes-test-log-inventory"

besctl stop

find . \( -name "*.log" -o -name "*site_map.txt" \) -print > "$TEST_LOG_INVENTORY"

tar -cvzf "/tmp/bes-autotest-${TRAVIS_JOB_NUMBER}-logs.tar.gz" -T "$TEST_LOG_INVENTORY"

./travis/upload-test-results.sh

if [ $test_status -ne 0 ]; then
    echo "# ERROR - 'make check' failed, exiting. $test_status: $test_status" >&2
    return $test_status;
fi
