#!/bin/bash

bes_numbers=${1:-"3.20.10-676"}


most_recent=$(grep -e "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" ChangeLog | head -1 | awk '{print $1;}')
echo "most_recent: ${most_recent}" >&2


update_text=$(gitlog-to-changelog --since="${most_recent}")
echo "update_text: " >&2
# echo "${update_text}"

#echo "--------------------------------------------------"
last_entry=$( echo "${update_text}" | grep -n "${most_recent}" | head -1 | awk '{split($1,a,":");print a[1]-1;}')
echo "last_entry: ${last_entry}" >&2
update_text=$(echo "${update_text}" | head -n ${last_entry})

#echo "--------------------------------------------------"

echo "##"
echo "## BES Version: ${bes_numbers}"
echo "##"
echo ""
echo "${update_text}"
echo ""
