
# Tcl/Expect code for the dispatch test.

# Make sure the global var dispatchTEST is set correctly.

global dispatchTEST
if ![info exists dispatchTEST] then {
    set dispatchTEST [transform ./kaka]
}

# The four `required' procs are _start, _load, _exit and _version.

proc cache_start { } {
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template01.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template02.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template03.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template04.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template05.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template06.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template07.txt"
    catch "exec /bin/cp -f testsuite/cache/template.txt testsuite/cache/bes_cache#usr#local#data#template08.txt"

    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template05.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template03.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template06.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template02.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template04.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template01.txt"
    catch "exec sleep 2"
    catch "exec /bin/echo \"update\" >> testsuite/cache/bes_cache#usr#local#data#template08.txt"

    dispatch_start
}

proc dispatch_start { } {
    global verbose
    global dispatchTEST
    global comp_output
    global spawn_id

    if {$verbose >= 1} {
	send_user "Testing dispatch ...\n"
	exp_internal 1
    }

    catch "exec $dispatchTEST" comp_output

    if {$verbose >= 1} {
	send_user "Comp output:\n$comp_output\n"
    }
}

proc dispatch_load {} {
}

proc dispatch_exit {} {
    send -raw ""
}

proc dispatch_version {} {
    send_user "dispatch test suite 1.0\n"
}
