Attributes {
    SST1 {
        lon {
            String units "degrees_east";
            String long_name "longitude";
        }
        lat{
            String units "degrees_north";
            String long_name "latitude";
        }
    }

    SST2 {
        lon {
            String units "degrees_E";
            String long_name "longitude";
        }
        lat{
            String units "degrees_N";
            String long_name "latitude";
        }
    }

    SST3 {
        lon {
            String units "degree_east";
            String long_name "longitude";
        }
        lat{
            String units "degree_N";
            String long_name "latitude";
        }
    }
}
     