Attributes {
    HDF_GLOBAL {
    }
    CoreMetadata {
        OrbitNumber {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RangeBeginningDate {
            String Value "2000/10/03";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RangeBeginningTime {
            String Value "00:00:00";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RangeEndingDate {
            String Value "2000/10/04";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RangeEndingTime {
            String Value "00:00:00";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        GranulePointer {
            String Value "3B42.001003.5.HDF";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ShortName {
            String Value "Surface Rain from Geostationary Satellites C";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SizeMBECSDataGranule {
            Float64 Value 0.220007;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LongitudeOfMaximumLatitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SpatialCoverageType {
            String Value "Horizontal";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EllipsoidName {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EquatorialRadius {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DenominatorFlatteningRatio {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitalModelName {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SemiMajorAxis {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MeanAnomaly {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RightAscensionNode {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ArgumentOfPerigee {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        Eccentricity {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        Inclination {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EpochTime {
            String Value "99:99:99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EpochDate {
            String Value "9999/99/99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EpochMillisec {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        WestBoundingCoordinate {
            Int32 Value -180;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EastBoundingCoordinate {
            Int32 Value 180;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        NorthBoundingCoordinate {
            Int32 Value 40;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SouthBoundingCoordinate {
            Int32 Value -40;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CenterLatitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CenterLongitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadiusValue {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LatitudeResolution {
            String Value "1deg";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LongitudeResolution {
            String Value "1deg";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        GeographicCoordinateUnits {
            String Value "Decimal Degrees";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        TemporalRangeType {
            String Value "Continuous Range";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        QualityAssuranceParameterName {
            String Value "ScienceQualityFlag";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        QualityAssuranceParameterValue {
            String Value "NOT BEING INVESTIGATED";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ReprocessingActual {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        BrowsePointer {
            String Value "3B42_BR.001003.5.BRO";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ScienceContact {
            String Value "George Huffman";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MeanMotion {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitAdjustFlag {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        AttitudeModeFlag {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SolarBetaAngleAtBeginningOfGranule {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SolarBetaAngleAtEndOfGranule {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SensorAlignment {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SensorAlignmentChannelOffsets {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ScanPathModel {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ScanPathModelParam {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        EphemerisFileID {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
    }
    ArchiveMetadata {
        DataGaps {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        NumberOfDataGaps {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        AlgorithmVersion {
            String Value "4.51";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ProductVersion {
            Int32 Value 5;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        ToolkitVersion {
            String Value "5.7";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CalibrationCoefficientVersion {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MissingData {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        PercentOfBadOrMissingPixels {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MaximumValidValueofChannel {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MinimumValidValueofChannel {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MinMaxUnits {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitSize {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarWavelength {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        MinimumReflectivityThreshold {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        AlgorithmID {
            String Value "3B42m2";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DataAccuracy {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        InputFiles {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DateOfGenerationOfInputFiles {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DataCenterSourceOfInputFiles {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        GenerationDate {
            String Value "2000-11-14T09:43:10.000Z";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DayNight {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SolarChannelGains {
            String Value "(-9999.9,-9999.9,-9999.9,-9999.9)";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        TMIRolloverCoef {
            String Value "(-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9,-9999.9)";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitFirstScanUTCDate {
            String Value "9999/99/99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitFirstScanUTCTime {
            String Value "99:99:99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitFirstScanUTCMilliseconds {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitFirstSCSecs {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitFirstSCSubsecs {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitLastScanUTCDate {
            String Value "9999/99/99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitLastScanUTCTime {
            String Value "99:99:99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitLastScanUTCmilliseconds {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitLastSCSecs {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        OrbitLastSCSubsecs {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCFSeconds {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCFSubseconds {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCFflag {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LeapSecondsFlag {
            String Value "Data_Location", "Error processing EOS attributes", "Error processing EOS attributes";
            String PGE "Error processing EOS attributes";
            String Mandatory "FALSE";
        }
        RadarSiteName {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarCity {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarState {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarCountry {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        NumberOfVOS {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridOriginLatitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridOriginLongitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridOriginAltitude {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSpacingX {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSpacingY {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSpacingZ {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSizeX {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSizeY {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RadarGridSizeZ {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DZCal {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        GVL1C_Scale {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        Alpha {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RuntimeOptions {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        AnomalyFlag {
            String Value "NOT EMPTY";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        SoftwareVersion {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        DatabaseVersion {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        TotalQualityCode {
            String Value "NULL";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LongitudeOnEquator {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCDateOnEquator {
            String Value "9999/99/99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCTimeOnEquator {
            String Value "99:99:99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        UTCMillisecsOnEquator {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CenterScanUTCDate {
            String Value "9999/99/99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CenterScanUTCTime {
            String Value "99:99:99";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        CenterScanUTCMillisec {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        FirstScanLat {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        FirstScanLon {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LastScanLat {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        LastScanLon {
            Float64 Value -9999.9;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        NumberOfRainScans {
            Int32 Value -9999;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
    }
    DataGranule {
        String NewAttrib "
      Make sure we can add to renamed variable!
    ";
        PlanetaryGrid {
            relError {
                dim_0 {
                    String name "scan";
                }
                dim_1 {
                    String name "longitude";
                }
                dim_2 {
                    String name "latitude";
                }
            }
            precipitate {
                dim_0 {
                    String name "scan";
                }
                dim_1 {
                    String name "longitude";
                }
                dim_2 {
                    String name "latitude";
                }
            }
        }
    }
}
