#!/bin/bash

hostnport=52.207.248.86:8080
service_base="http://${hostnport}/opendap";
dmrpp_base="${service_base}/arch2.1";
ebs_base="${service_base}/ebs";

default_request="airs/AIRS.2015.01.05.L3.RetStd_IR001.v6.0.11.0.G15007130423.nc.h5.dmrpp.ascii?O3_VMR_TqJ_D"


reps=$1;
if [ ! "$reps" ] && [  ! -n "$reps" ]; then reps=10; fi
echo "reps: ${reps}";

#reps=10;
dmrpp_request="${2}";
if [ ! "$dmrpp_request" ] && [  ! -n "$dmrpp_request" ]; then dmrpp_request="${default_request}"; fi
echo "request: ${dmrpp_request}";


function timedGet() {
    url="${1}";
    time -p curl -s $url > /dev/null;
}


function doReps() {

    request="${1}";
    
    
    
    dmrpp_url="${dmrpp_base}/${dmrpp_request}";
    
    ebs_request=`echo ${dmrpp_request} | sed "s/.dmrpp//g"`
    ebs_url="${ebs_base}/${ebs_request}";
    
    echo "EBS - url: ${ebs_url}"
    let n=0;
    while [[ $n -lt $reps ]]
    do
        echo -n "${ebs_request}  " ;
        timedGet "${ebs_url}" 
        let n=n+1;
    done
    
    
    echo "DMRPP - url: ${dmrpp_url}"
    let n=0;
    while [[ $n -lt $reps ]]
    do
        echo -n "${dmrpp_request}  " ;
        timedGet "${dmrpp_url}" 
        let n=n+1;
    done
}




doReps "${dmrpp_request}"







