Attributes {
    GLOBAL {
        Metadata {
            String TIFFTAG_RESOLUTIONUNIT "2 (pixels/inch)";
            String TIFFTAG_XRESOLUTION "72";
            String TIFFTAG_YRESOLUTION "72";
        }
    }
    SRB1 {
        Float64 add_offset 0;
        Float64 scale_factor 1;
        String PhotometricInterpretation "Gray";
    }
    new_time {
        String units "days since 2000-01-01 00:00";
    }
}
