Attributes {
    GLOBAL {
        Float64 Northernmost_Northing 4255884.543802192;
        Float64 Southernmost_Northing 4224973.143255847;
        Float64 Easternmost_Easting 2358.211624949061;
        Float64 Westernmost_Easting -28493.16678441252;
        String GeoTransform "-28493.16678441252 60.02213698319374 0 4255884.543802192 0 -60.02213698319374";
        Metadata {
            String AREA_OR_POINT "Area";
        }
        String spatial_ref "PROJCS[\"unnamed\",GEOGCS[\"NAD27\",DATUM[\"North_American_Datum_1927\",SPHEROID[\"Clarke 1866\",6378206.4,294.978698213898,AUTHORITY[\"EPSG\",\"7008\"]],AUTHORITY[\"EPSG\",\"6267\"]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4267\"]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"standard_parallel_1\",33.75],PARAMETER[\"central_meridian\",-117.333333333333],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]";
    }
    band_1 {
        String PhotometricInterpretation "Gray";
    }
}
