name: ubuntu-latest build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PWD_DIR: /home/runner

    steps:
    - uses: actions/checkout@v2
      with:
        submodules : true 
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install -o Acquire::Retries=3 doxygen graphviz wget gfortran
    - name: cache-hyrax-dependencies
      id: cache-hyrax-dependencies
      uses: actions/cache@v2
      with:
        path: ~/hyrax-dependencies
        key: hyrax-dependencies-${{ runner.os }}

    - name: build-hyrax-dependencies
      if: steps.cache-hyrax-dependencies.outputs.cache-hit != 'true'
      run: |
        set -x
        git clone git@github.com:OPENDAP/hyrax-dependencies.git
        cd hyrax-dependencies
        export prefix=/home/runner/hd1
        make 
        cd ..
    - name: configure
      run: |
        set -x
        autoreconf -i
