name: ubuntu-latest build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PWD_DIR: /home/runner

    steps:
    - uses: actions/checkout@v2
      with:
        submodules : true 
    - name: Installs
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install -o Acquire::Retries=3 netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev libdap-dev libgdal-dev
    - name: cache-hdf4
      id: cache-hdf4
      uses: actions/cache@v2
      with:
        path: ~/hdf4
        key: hdf4-${{ runner.os }}-fPIC-4.2.13

    - name: build-hdf4
      if: steps.cache-hdf4.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz &> /dev/null
        tar zxf hdf-4.2.13.tar.gz
        cd hdf-4.2.13
        export CFLAGS=-fPIC
        ./configure --disable-netcdf --prefix=${PWD_DIR}/hdf4 
        make all 
        sudo make install clean
        cd ..
    - name: cache-hdfeos2
      id: cache-hdfeos2
      uses: actions/cache@v2
      with:
        path: ~/hdfeos2
        key: hdfeos2-${{ runner.os }}-fPIC-19v1.00

    - name: build-hdfeos2
      if: steps.cache-hdfeos2.outputs.cache-hit != 'true'
      run: |
        set -x
        wget -O hdfeos2_19.zip https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos/ce2beacbb1ab8471a9a207def005d559f0ab725b9a4f1b1525cbee3d20aab5b0?response-content-disposition=attachment%3B%20filename%3D%22hdfeos2_19.zip%22%3B%20filename*%3Dutf-8%27%27hdfeos2_19.zip &> /dev/null
        ls -l
        unzip hdfeos2_19.zip
        cd hdfeos2_19/hdfeos2.19/hdfeos
        chmod ug+x configure
        export CPPFLAGS="-I/home/runner/hdf4/include"
        export LDFLAGS="-L/home/runner/hdf4/lib"

        CFLAGS=-fPIC ./configure  --enable-install-include --prefix=${PWD_DIR}/hdfeos2
        make
        sudo make install clean
        cd ..
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ~/hdf5
        key: hdf5-${{ runner.os }}-1.10.6

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.6.tar.gz
        pushd hdf5-1.10.6
        ./configure --prefix=/home/runner/hdf5 --disable-tools --disable-fortran --disable-cxx 
        make
        sudo make install
        popd
    - name: cache-stare
      id: cache-stare
      uses: actions/cache@v2
      with:
        path: ~/stare
        key: stare-${{ runner.os }}-0.16.3

    - name: build-stare
      if: steps.cache-stare.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/SpatioTemporal/STARE/archive/0.16.3-beta.tar.gz  &> /dev/null
        tar zxf 0.16.3-beta.tar.gz
        cd STARE-0.16.3-beta/
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
        make all
        sudo make install
        cd ../..
    - name: configure
      run: |
        set -x
        autoreconf -i
        export CPPFLAGS="-I/home/runner/stare/include"
        export LDFLAGS="-L/home/runner/stare/lib"
        ./configure --with-hdf4=/home/runner/hdf4 --with-hdfeos2=/home/runner/hdfeos2 --with-hdf5=/home/runner/hdf5
        make 
