# Copied from the libdap4 main.yml workflow written by Emmanuel Babalola.
# jhrg 2/24/21

name: Main build workflow

env:
  prefix: ${{ github.workspace }}/build
  jobs: 16

on:
  push:
    branches: [ actions-build ]
  pull_request:
    branches: [ actions-build ]
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Set PATH
        run: echo "$prefix/bin:$prefix/deps/bin" >> $GITHUB_PATH
        #run: echo "$prefix/deps/bin:$prefix/bin" >> $GITHUB_PATH
        
      - name: Packages
        run: sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev libfl-dev gcovr


      - name: cache-deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: $prefix/deps
          key: deps-${{ runner.os }}

      - name: build dependencies
        if: steps.cache-bison.outputs.cache-hit != 'true'
        run: |
          echo "PATH: $PATH"
          git clone https://github.com/OPENDAP/hyrax-dependencies
          cd hyrax-dependencies
          make --jobs=$jobs

      - name: cache-libdap4
        id: cache-libdap4
        uses: actions/cache@v2
        with:
          path: $prefix
          key: libdap4-${{ runner.os }}

      - name: build libdap4
        if: steps.cache-libdap4.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/OPENDAP/libdap4
          cd libdap4
          autoreconf --force --install --verbose
          ./configure --prefix=$prefix --enable-developer
          make --jobs=$jobs
          make check --jobs=$jobs
          make install

      - name: build bes
        run: |
          git clone --recurse-submodules https://github.com/OPENDAP/bes
          cd bes
          autoreconf --force --install --verbose
          ./configure --prefix=$prefix --with-dependencies=$prefix/deps --enable-developer
          make --jobs=$jobs
          make install

     # - name: checkout
     #   uses: actions/checkout@v2
     #   with:
     #     submodules: 'recursive'

     # - name: autoreconf
     #   run: autoreconf --force --install --verbose

     # - name: configure
     #   run: |
     #     ./configure --prefix=$prefix --with-dependencies=$prefix/deps --enable-developer | tee foo
     #     grep -e "^checking for libdap .* yes$" foo  

     # - name: Make
     #   run: make -j7

     # - name: Check
     #   run: make -j7 check

     # - name: Install
     #   run: make install
