# Test the BES "show" interface.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from bescmdln_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.


bescmdln_start "testsuite/show/show_02.bescmd"
compare_stdout "testsuite/show/show_02.bescmd.baseline" "show info interface" 1 match

